# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # Prevent clashes with multiple VM's running concurrently
  config.vm.network :forwarded_port, guest: 22, host: 2222, id:"ssh", auto_correct: true

  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  #config.vm.box = "ubuntu/trusty64"
  config.vm.box = "magentys/devops-docker"

  config.vm.synced_folder "../", "/home/vagrant/project", create:true

  #TODO - Environment variables -> ACCESS_KEYS
  # https://github.com/mitchellh/vagrant/issues/2064

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
  
  #config.vm.provision "file", source: "~/.ssh/sample-cloud-formation.pem", destination: ".ssh/sample-cloud-formation.pem" 
  #config.vm.provision "file", source: "~/.aws/credentials", destination: "/home/vagrant/.aws/credentials"
end

